# Name of model, loss, and optimizer.
title: diditwork
prj_dir: /home/dewdrop/pyuv/scqtest/nm
wandb_cfg:
  project: qbml
  entity: froggycham-cu-boulder-chemistry
  job_type: training
  name: diditwork
  config:
    n_encoders: 1
    batch_size: 10
    learning_rate: 1e-4
    weight_decay: 0
    loss_nvp: 1e-5
    epochs: 200
    input_seq_len: 500
    target_seq_len: 400
    rectifier: gelu
    block_size: 500
cfg_info:
  device: cpu
  model: qubitml.ml.transformer.Transformer()
  loss_fn: qubitml.ml.lossfuncs.MSELoss_Positive_Definite
  optimizer: torch.optim.Adam
# What are the sequence lengths and how to partition the dataset.
dataset:
  split: [0.9, 0.1]
set_path: /home/dewdrop/pyuv/scqtest/nm/data/mnm/mnm.ds
